import { useState, type FormEvent } from 'react';
import { Navigate } from 'react-router-dom';
import { Input } from '../../../components/ui/Input';
import { Pin } from '../../../components/ui/Pin';
import { useAuth } from '../hooks/useAuth';
export function AuthForm(){const [mode,setMode]=useState<'login'|'register'>('login');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const {user,login,register}=useAuth();
  if(user)return <Navigate to="/" replace/>;
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);const input={name:String(data.get('name')??''),email:String(data.get('email')),password:String(data.get('password'))};try{await (mode==='login'?login(input):register(input));}catch(err){setError(err instanceof Error?err.message:'خطایی پیش آمد');}finally{setBusy(false)}}
  return <section className="relative w-full max-w-sm -rotate-1 rounded-sm bg-paper-yellow px-8 pb-8 pt-11 shadow-paper"><Pin className="-top-2 left-1/2 -translate-x-1/2"/><div className="text-center"><h1 className="font-display text-5xl">لحظه</h1><p className="mb-7 text-xs leading-6 text-soft-ink">جایی برای سنجاق کردن لحظه‌هایی که دوست نداری فراموش کنی 📌</p>
    <div className="mb-6 flex justify-center gap-2"><button onClick={()=>setMode('login')} className={`rounded-full border-2 border-ink px-5 py-1.5 text-sm font-bold ${mode==='login'?'bg-ink text-paper-yellow':''}`}>ورود</button><button onClick={()=>setMode('register')} className={`rounded-full border-2 border-ink px-5 py-1.5 text-sm font-bold ${mode==='register'?'bg-ink text-paper-yellow':''}`}>ثبت‌نام</button></div></div>
    <form onSubmit={submit} className="space-y-4">{mode==='register'&&<label className="block text-xs font-bold text-soft-ink">نام<Input name="name" required placeholder="نام تو" className="mt-1"/></label>}<label className="block text-xs font-bold text-soft-ink">ایمیل<Input name="email" type="email" required placeholder="you@example.com" className="mt-1"/></label><label className="block text-xs font-bold text-soft-ink">رمز عبور<Input name="password" type="password" minLength={8} required placeholder="••••••••" className="mt-1"/></label>{error&&<p className="text-xs font-bold text-pin-red">{error}</p>}<button disabled={busy} className="w-full rounded-full bg-pin-red py-3 font-bold text-white active:scale-95">{busy?'لحظه‌ای…':mode==='login'?'ورود به لحظه':'ساخت حساب و ورود'}</button></form></section>}
